### PR TITLE
Implement code for the click event

### PR DESCRIPTION
**Pull request by kbandla**
This will create a 'LazyEye' fieldset with textboxes for each extracted category. This fieldset is then appended to the body tag, which will display at the end of the page.

### CODE REVIEW

**Comment by 9b** [comment]
I am good with this. Is it possible to clean up the JS, so it's properly spaced and formatted. The current proposed changes make it difficult to read. Additionally, it would be nice if the "show results" was controlled via the options page.

**Comment by 9b** [comment]
Looks like it was just an issue when viewing on Github. The fieldsets itself needs a lot of style work, but I can take care of that in the future. Thinking it would be more beneficial in having a fixed bar pushed to the top where users could just "click-to-copy" each category. It's unlikely they will be cherry-picking from the textareas anyway.

**Comment by kbandla** [comment]
One problem with re-writing the page (like is done in this patch) is that the page's original CSS will apply to any changes. We can get around that, but its more work. 
I like the "click-to-copy" idea. Lastly, as far an style work goes, I cant help much - I cant UI :(

**Comment by 9b** [comment]
You can push the styles local to the object itself like you did. I am experimenting now.

**Comment by 9b** [comment]
Alright, re-styled. 

new toolbar

**Comment by kbandla** [comment]
That looks so much cleaner!

**Pull request merged**
